/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarTabs: typeof import('./src/components/CarTabs.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageSlider: typeof import('./src/components/ImageSlider.vue')['default']
    OrderNow: typeof import('./src/components/OrderNow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
  }
}
